### ISSUE TITLE
Logo improvement proposal

### ISSUE THREAD

**Issue by CallMeFib3r** [bowserf/behaviortracker#1]
Hi there!

As a graphic designer (hobbyist) I try to get the most out of my day and your project would be very helpful for me. That's one of the reasons why I decided I wanted to contribute your app, in the form of a redesign of your current logo. Before we proceed I want to say that this logo is completely free of charge so you should consider it as a contribution. I will be getting rewarded on the utopian.io platform so don't worry about the monetary aspect.

Alright let's take a look at the logo I came up with. 

Before I started on the redesign I checked what comptetiors in the appstore were doing and I noticed all of the logos were pretty similar. Therefore I came up with something fresh.
For this logo I attempted to combine the productivity element of your app along with the functionality element. I displayed the productivty in the form of a cute little plant, it represents growth which is a direct successor of productivity in my eyes. The small leaves also serve as the hands of a clock/timer.
![presentation-03](https://user-images.githubusercontent.com/37731582/38782179-a8fe762c-40ef-11e8-8278-3a49fb71ddf0.png)

Let me know what you think!

Kind regards,

Fiber

**Comment by bowserf** [comment]
Hello Fiber,

First of all, it's a real pleasure to see someone contributing to this project, so thank you to take time to look at it!

As you probably saw, I'm more a developer than a designer so any help on this domain is very appreciated!

About your logo, ideas behind it are really nice and have a real meaning compare to a color timer =)

I really like the idea of a growing plant to show the evolution and improvement of the person who will use the application. Its integration with the timer is so perfect to my eyes !

I have one comment about your logo: the design of the application follows material design rules, with flat color, shadows and simple shape. Your logo contrasts a little bit with this idea.

Anyway, it would be a pleasure to integrate your work. As you said, all applications in this domain have same kind of logo. With yours, the application could stand out !

Have a nice day,

Bowser_f

**Comment by CallMeFib3r** [comment]
You're welcome Bowser_f, I'm glad I can help you out!
I went ahead and included everything you mentioned into the original idea. Do you like everything color wise? If you have some other things you would like me to change I will happily do so! If not feel free to send me all the sizes and file types you want and I will send you a folder with all the files you need.
I hope you like it!
![chronograph_v2-05-05](https://user-images.githubusercontent.com/37731582/38892151-bff08814-4286-11e8-9bc8-ecf896fe4a32.png)

**Comment by bowserf** [comment]
Hi Fib3r ,

Sorry for the long delay of my answer and thank you to take into account my commentaries.
It's really more material design than the first version. Colors are really nice like this. 

If you accept a commentary, due to the form you choose for this icon, it will never totally respect material design but it's okay! Material icon is composed of really simple shapes but I don't think it's would be easy to transform a leaf in a simple form.

Unless you have an idea for this last commentary, otherwise I will send you information about the size.

Again, thank you to contribute to this project !

**Comment by CallMeFib3r** [comment]
Hi @bowserf,

Glad you like the improvements on the logo and new colors so far! 

I completely get that you're going for a material design look. But I'm not sure if it's possible to boil down the shape even more without losing recognizability. If I boil the shapes down even more I feel like the end users will be confused if you know what I mean. Just my 2c.

**Comment by bowserf** [comment]
I'm totally agree with you ! Let's keep it that way !

In the last version of Android, Google developers introduced "adaptive icon" (https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive?authuser=0)

It's now possible to change the background of an icon from circle to square to rectangle. The icon is composed of 2 layers. It would be perfect if you can provide to me the foreground icon (with the timer) and with it, I will be able to generate adaptive icon and icons for previous Android versions. The shadow must be included in the foreground icon.

The tools allowing to generate icons can also generate play store icon. It also allows to scale the image so normally, if you provide to me just one big image, all should be okay but I'm not sure of the result with the downscale for small icons.

We can try with a 512x512 image where you respect margins you apply to your foreground image and we will see the result if you want.

**Comment by CallMeFib3r** [comment]
Alright great. I like the idea of adaptive icons. You can find the 512x512 file over here https://drive.google.com/open?id=1AjnuVyefqGWDFOiKslcsd2DaJPpzTExv (I will place all the source files over there as well. I uploaded a 512x512 .png file including the shadows of the icon itself, the background is transparent so normally there shouldn't be a problem. If anything is not right don't hesitate to let me know and I will upload the right files.

**Comment by CallMeFib3r** [comment]
I've also added a little image for your repository. I've added it to the drive folder (link is above).
![github_repo-01](https://user-images.githubusercontent.com/37731582/39676996-57ad60d6-5174-11e8-91fe-e3c78f57b646.png)

**Comment by bowserf** [comment]
It's good ! I finally found time to do a release with your icon ! :tada:
Thank you so much for all the resources you shared to me !
